### PR TITLE
fix extra json marshalling of error cases #12

### PR DESCRIPTION
**Pull request by aiba**
Attempted fix for #12 

It compiles, but I'm not sure how to test it.

### CODE REVIEW

**Comment by lispyclouds** [comment]
Thanks! You can try loading the compiled binary with `(pods/load-pod "./pod-babashka-fswatcher")` and see https://github.com/babashka/pod-babashka-fswatcher/blob/main/test/script.clj as example. Then you should be able to hit it with your errors.

**Comment by aiba** [comment]
Thank!  I restarted my computer and can no longer reproduce the fs watcher errors, so i'm not sure how to test the error code paths.  I think if someone who knows golang can sanity check this commit, then it's probably no harm to merge.

**Comment by lispyclouds** [comment]
Interesting, will find some time to review it!

**Comment by lispyclouds** [comment]
@aiba could you send us the code that was crashing it? I'd wanna look into if its indeed a bug which needs addressing.

**Comment by lispyclouds** [comment]
I would want to add it to the tests even if it doesn't crash it now, just to be extra sure!

**Comment by aiba** [comment]
I was able to reproduce and confirm that this PR fixes my issue.

Now the fs-watch handler function (in clojure) receives `{:error "too many open files"}` which was apparently the issue for me.

If you want to reproduce this, all you have to do is reach the open files limit on a watched directory.  (I'm still not sure how to artificially create this situation.  I seem to just wait for it to happen.)

**Comment by borkdude** [comment]
Thanks, that is sufficient.

**Pull request merged**
